# use df generated by get-pkgs.R to install packages that aren't computer currently.
library(tidyverse)
pkgs_df <- read_csv("pkgs.csv") %>%
	glimpse()

# install packages not found
packages <- pkgs_df$package
if (length(setdiff(packages, rownames(installed.packages()))) > 0) { # checks if there is a difference between currently installed packages and packages in csv
	install.packages(setdiff(packages, rownames(installed.packages())))  # installs the packages that are in csv but not computer
}